-- MySQL Script generated by MySQL Workbench
-- Mon Jan 15 12:03:27 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projet_dbpy
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `projet_dbpy` ;

-- -----------------------------------------------------
-- Schema projet_dbpy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projet_dbpy` DEFAULT CHARACTER SET utf8 ;
USE `projet_dbpy` ;

-- -----------------------------------------------------
-- Table `projet_dbpy`.`MiniGame`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_dbpy`.`MiniGame` ;

CREATE TABLE IF NOT EXISTS `projet_dbpy`.`MiniGame` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `MiniGame_name` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet_dbpy`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_dbpy`.`users` ;

CREATE TABLE IF NOT EXISTS `projet_dbpy`.`users` (
  `id` INT NOT NULL,
  `username` VARCHAR(15) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet_dbpy`.`results`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projet_dbpy`.`results` ;

CREATE TABLE IF NOT EXISTS `projet_dbpy`.`results` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(20) NOT NULL,
  `date et heure` DATETIME NOT NULL,
  `temp` DECIMAL NOT NULL,
  `nb_ok` DECIMAL(3) NOT NULL,
  `nb_trials` DECIMAL(3) NOT NULL,
  `MiniGame_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_results_MiniGame_idx` (`MiniGame_id` ASC) VISIBLE,
  INDEX `fk_results_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_results_MiniGame`
    FOREIGN KEY (`MiniGame_id`)
    REFERENCES `projet_dbpy`.`MiniGame` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_results_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `projet_dbpy`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
