-- MySQL Script generated by MySQL Workbench
-- Mon Dec  4 08:41:55 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`MiniGame`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MiniGame` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MiniGame` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `MiniGame_name` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`results`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`results` ;

CREATE TABLE IF NOT EXISTS `mydb`.`results` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(20) NOT NULL,
  `date et heure` DATETIME NOT NULL,
  `temp` DECIMAL NOT NULL,
  `nb_ok` DECIMAL(3) NOT NULL,
  `nb_trials` DECIMAL(3) NOT NULL,
  `MiniGame_id` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_results_MiniGame_idx` (`MiniGame_id` ASC) VISIBLE,
  CONSTRAINT `fk_results_MiniGame`
    FOREIGN KEY (`MiniGame_id`)
    REFERENCES `mydb`.`MiniGame` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
